name = "Unnamed RPG Pack"
author = "jadelily18"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f63a2b1406fd5d28b4c7c97946df07b6ea7ddb1b173c7df7f73e78bd3a9cd081"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
